apiVersion: v1
kind: Pod
metadata:
  generateName: my-test-pod-
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"name": "ib-sriov-network"}]'
spec:
  restartPolicy: OnFailure
  containers:
    - image: mellanox/rping-test
      imagePullPolicy: IfNotPresent
      name: my-test-ctr
      securityContext:
        capabilities:
          add: [ "IPC_LOCK" ]
      command:
        - sh
        - -c
        - |
          sleep 1000000
      resources:
        limits:
          mellanox.com/mlnx_sriov_rdma_ib: 1
        requests:
          mellanox.com/mlnx_sriov_rdma_ib: 1
